### ISSUE TITLE
Add Ambient audio

### ISSUE THREAD

**Issue by alexei1118** [edwardcohen/babytimer#10]
Add ambient audio

**Comment by alexei1118** [comment]
The audio file codec is invalid for playing in iOS. Please remake it as others with following information.
   Audio
      Format : MPEG Audio
      Format version : Version 1
      Format profile : Layer 3
      Mode : Joint stereo
      Mode extension : MS Stereo
      Bit rate : 192 Kbps
      Channel(s) : 2 channels
      Sampling rate : 48.0 KHz
      Compression mode : Lossy
      Stream size : 189 KiB (97%)

**Comment by alexei1118** [comment]
And it's volume is very low

**Comment by edwardcohen** [comment]
Loop is glitchy.
