### ISSUE TITLE
Final Noises

### ISSUE THREAD

**Issue by edwardcohen** [edwardcohen/babytimer#19]
1. white noise 2) brown noise 3) pink noise 4) waterfall 5) ambient

**Comment by edwardcohen** [comment]
Please make sure there are no gaps.

**Comment by alexei1118** [comment]
You didn't give brown and pink noise with no gaps

**Comment by edwardcohen** [comment]
Try these: https://www.dropbox.com/sh/v8wpvk25mankfd7/AADAQvazxKAxgCuviYDOsn4ba?dl=0

**Comment by edwardcohen** [comment]
Try this Pink Noise: https://www.dropbox.com/s/hsefngmu9omc3n1/Pink%20Noise%20Loop.mp3?dl=0

And this Brown Noise https://www.dropbox.com/s/4n9vx1c5kiloyrb/Brown%20Noise_01.mp3?dl=0
