### ISSUE TITLE
Settings Panel Color

### ISSUE THREAD

**Issue by edwardcohen** [edwardcohen/babytimer#2]
Please fix this (https://www.dropbox.com/s/rxezqe6ngvvx0y8/Settings%20annotated%20goodnight%20%20PM.jpeg?dl=0) - background color of settings panel

**Comment by edwardcohen** [comment]
New Colors: Make the Font Color and the Apple Switch UI (this is currently green) color: HEX 131D77. R:19 G:29 B:119

**Comment by edwardcohen** [comment]
Make the Settings Panel. R: 200 G:194 B: 226 A: 81

**Comment by alexei1118** [comment]
I changed colors, and found that color of corner  is not clear to see. Please check it and decide to fix corner color issue or not.

**Comment by edwardcohen** [comment]
looks good. but please change the font color  and apple green color. 

On Tue, Aug 16, 2016 at 10:12 AM -0700, "alexei-laine" notifications@github.com wrote:

I changed colors, and found that color of corner  is not clear to see. Please check it and decide to fix corner color issue or not.
