### ISSUE TITLE
Noises Loop Glitch

### ISSUE THREAD

**Issue by edwardcohen** [edwardcohen/babytimer#3]
Please make sure that there is no gap in the noises when they loops

**Comment by alexei1118** [comment]
Please check all noise mp3 files. It may have a short gap at start or end of play.
Before, I thought there is a problem at start and end of noise file, so I cut out 1s start and 1s end, then it worked with no gap.
So you can do like I did.
Don't forget to check all files during all playing. I found some noise files have a peek in the middle.

**Comment by edwardcohen** [comment]
The files seem fine on my end...

**Comment by alexei1118** [comment]
please cut out 1s of start & end for every noise, and send me files. I will put them source and you can test.

**Comment by edwardcohen** [comment]
So 8 seconds?
